apiVersion: v1
kind: Service
metadata:
  name: {{ include "bitcoin-core.fullname" . }}
  labels:
    {{- include "bitcoin-core.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.rpcPort }}
      targetPort: rpc
      protocol: TCP
      name: rpc
    - port: {{ .Values.service.p2pPort }}
      targetPort: p2p
      protocol: TCP
      name: p2p
  selector:
    {{- include "bitcoin-core.selectorLabels" . | nindent 4 }}
